# Generated by Django 6.0.4 on 2026-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_ticket_row_seat_flight_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ('-rows', '-seats_in_row')},
        ),
        migrations.AddField(
            model_name='airplane',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='airport',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='crew',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
