# Generated by Django 6.0.4 on 2026-05-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_airplane_options_airplane_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='airplanetype',
            table='airplane_type',
        ),
    ]
