# Generated by Django 6.0.4 on 2026-05-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_remove_route_slug_alter_airplanetype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airplanetype',
            table='airport_airplane_type',
        ),
    ]
