# Generated by Django 6.0.4 on 2026-05-16 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_alter_airplanetype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airplanes', to='airport.airplanetype'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='slug',
            field=models.SlugField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='slug',
            field=models.SlugField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='airport',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='crew',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='slug',
            field=models.SlugField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airport.airplane'),
        ),
    ]
