# Generated by Django 6.0.4 on 2026-05-26 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_airplane_description_airport_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='airplanetype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='slug',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='airport.airplanetype'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seats_in_row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airport.airplane'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
