# Generated by Django 6.0.4 on 2026-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_remove_airplane_slug_remove_airplanetype_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('-departure_time', '-arrival_time')},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('flight_id', 'row', 'seat')},
        ),
    ]
