# Generated by Django 6.0.4 on 2026-05-28 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_alter_flight_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('country', 'city', 'iata_code')},
        ),
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(default=None, max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='airport',
            constraint=models.UniqueConstraint(fields=('name', 'country', 'city'), name='name_country_city_unique'),
        ),
    ]
