# Generated by Django 6.0.4 on 2026-05-29 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0009_alter_airport_options_airport_iata_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(null=True, unique=True, validators=[django.core.validators.RegexValidator(message='IATA code must be a three-letter identifier in upper case', regex='[A-Z]{3,3}')]),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['row', 'seat'], name='row_seat_idx'),
        ),
        migrations.AlterConstraint(
            model_name='airport',
            name='name_country_city_unique',
            constraint=models.UniqueConstraint(fields=('name', 'country', 'city'), name='name_country_city_unique', violation_error_message='Airport with this name, country and city exists.'),
        ),
        migrations.AlterConstraint(
            model_name='flight',
            name='departure_time_lte_arrival_time',
            constraint=models.CheckConstraint(condition=models.Q(('departure_time__lte', models.F('arrival_time'))), name='departure_time_lte_arrival_time', violation_error_message='Departure time must be less than or equal arrival time'),
        ),
        migrations.AlterConstraint(
            model_name='route',
            name='source_destination_unique',
            constraint=models.UniqueConstraint(fields=('source', 'destination'), name='source_destination_unique', violation_error_message='Route with this source and destination exists.'),
        ),
        migrations.AlterConstraint(
            model_name='ticket',
            name='row_seat_flight_unique',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'flight'), name='row_seat_flight_unique', violation_error_message='Ticket with this row, seat and flight exists.'),
        ),
    ]
