# Generated by Django 6.0.4 on 2026-06-01 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_alter_airport_iata_code_ticket_row_seat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(null=True, unique=True, validators=[django.core.validators.RegexValidator(message='IATA code must be a three-letter identifier in upper case', regex='^[A-Z]{3,3}$')]),
        ),
    ]
