# Generated by Django 6.0.4 on 2026-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0011_alter_airport_iata_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
